name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/jod'
      - run: npm install
      - run: npm test